AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String
    Default: AdastraEnvironment

Resources:
  # DP admin user
  DPAdminUser:
    Type: AWS::IAM::User
    Properties: 
      Groups: 
        - !Ref DPAdminGroup
      UserName: DataPlatformAdmin

  DPAdminGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: DPAdminGroup
      ManagedPolicyArns: # list of ARNs of IAM managed policies that you want to attach to the role
        - arn:aws:iam::aws:policy/AmazonRDSFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
        - arn:aws:iam::aws:policy/AmazonVPCFullAccess
        - arn:aws:iam::aws:policy/service-role/AmazonEMRServicePolicy_v2
      Path: "/dpadmin/"
      Policies:
      - PolicyName: dpadmin
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - "s3:*"
              Resource: "*"
            - Effect: Allow
              Action:
                - ec2:*
              Resource: "*"
            - Effect: Allow
              Action:
                - iam:*
              Resource: "*"
            - Effect: Allow
              Action:
                - airflow:*
              Resource: "*"
            - Effect: Allow
              Action:
                - athena:*
              Resource: "*"
            - Effect: Allow
              Action:
                - acm:*
              Resource: "*"
            - Effect: Allow
              Action:
                - s3:*
              Resource: "*"
            - Effect: Allow
              Action:
                - glue:*
              Resource: "*"
            - Effect: Allow
              Action:
                - s3-object-lambda:*
              Resource: "*"
            - Effect: Allow
              Action:
                - ses:*
              Resource: "*"
            - Effect: Allow
              Action:
                - secretsmanager:*
              Resource: "*"
              

  # Airflow role
  AirflowExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - airflow-env.amazonaws.com
                - airflow.amazonaws.com
            Action:
             - "sts:AssumeRole"
      Path: "/service-role/"

  AirflowExecutionPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Roles:
        - !Ref AirflowExecutionRole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: airflow:PublishMetrics
            Resource:
              - !Sub "arn:aws:airflow:${AWS::Region}:${AWS::AccountId}:environment/${EnvironmentName}"
          - Effect: Allow
            Action:
              - "s3:*"
            Resource: "*"
          - Effect: Allow
            Action:
              - logs:DescribeLogGroups
            Resource: "*"
          - Effect: Allow
            Action:
              - logs:CreateLogStream
              - logs:CreateLogGroup
              - logs:PutLogEvents
              - logs:GetLogEvents
              - logs:GetLogRecord
              - logs:GetLogGroupFields
              - logs:GetQueryResults
              - logs:DescribeLogGroups
            Resource: "*"
          - Effect: Allow
            Action:
              - glue:*
            Resource: "*"
          - Effect: Allow
            Action: cloudwatch:PutMetricData
            Resource: "*"
          - Effect: Allow
            Action:
              - ses:*
            Resource: "*"
          - Effect: Allow
            Action:
              - secretsmanager:*
            Resource: "*"
          - Effect: Allow
            Action:
              - sqs:ChangeMessageVisibility
              - sqs:DeleteMessage
              - sqs:GetQueueAttributes
              - sqs:GetQueueUrl
              - sqs:ReceiveMessage
              - sqs:SendMessage
            Resource:
              - !Sub "arn:aws:sqs:${AWS::Region}:*:airflow-celery-*"
          - Effect: Allow
            Action:
              - kms:Decrypt
              - kms:DescribeKey
              - "kms:GenerateDataKey*"
              - kms:Encrypt
            NotResource: !Sub "arn:aws:kms:*:${AWS::AccountId}:key/*"
            Condition:
              StringLike:
                "kms:ViaService":
                  - !Sub "sqs.${AWS::Region}.amazonaws.com"

Outputs:

  AirflowExecutionRoleArn:
    Value: !GetAtt AirflowExecutionRole.Arn
    Export: 
      Name: AirflowExecutionRoleArn